import * as protobuf from 'protobufjs';
//import { BleManager } from 'react-native-ble-plx'
/**
 * Analyzing the ways to handle Protobuf serial communication
 */

// Load the file containing all the protobuf functions generated by the protoc compiler
var messages = require('../Resources/IBDC_pb');

// Create a new message of a type defined in IBDC.proto
var deviceStatus = new messages.DeviceStatus();

// Set message fields
deviceStatus.setBatteryPercent(50);
deviceStatus.setProtocolVersion(2);
deviceStatus.setPendingEvents(10);
deviceStatus.setStorageAvailablePercent(35);

// Serialize the message into binary data (in protobuf wire format).
console.log('payload as a json object', deviceStatus.toObject());
console.log('payload as proto encoded bytes', deviceStatus.serializeBinary());
let bytes: Uint8Array = [0, 3, 7, 12, 4];

// De-serialize the message
let message = messages.DeviceStatus.deserializeBinary(deviceStatus.serializeBinary());
console.log('message decoding as a json object', message.toObject());

/** Serializing and de-serializing data is not a problem when the type information is known before runtime.
*   Issues arise when the data type being received over the connection is dynamic. Two issues are:
*       1. How will each message be de-limited from the all the other messages in the received buffer?
*       2. How will we know which de-serializing function to use if the type of message is not known?
*/


// A potential solution to the problem of de-limiting multiple messages sent to the device at once is ->
// As messages are received, each Uint8Array(byte array) is added to the buffer. This creates the
// concept of a defined start-end to each message. Each message is an element in the buffer.
let buffer: Uint8Array[];

//


