import * as protobuf from 'protobufjs'
import { BleManager } from 'react-native-ble-plx'
import * as fs from 'fs'

/**
 * This function acts as a way to get device information and return it as an object
 * This would only be able to be called after the BLEManager discovers the target device and connects
 */
function getDeviceStatus(): String {
    // This object can be edited easily. Each key-val pair from this object will be printed to the comms log.
    let deviceStatus: Object = {
        isConnected: true
    }
    return Object.entries(deviceStatus);
};
/**
 * Analyzing the ways to handle Protobuf serial communication
 *
 * User Story Tasks
 *
 * Task#101 Validate incoming protobuf messages
 *
 * Task#88 Encapsulate data serialization logic
 *
 * Task#102 Create communication log
 */

/** This text summarizes the structure and level of detail encapsulated in each UUID
 * Service UUIDs: Unique IDs for each service provided by the peripheral (e.g., Heart Rate Service, Battery Service).
 *  - To Do: Find the UUID associated with the bluetooth serial communication device.
 *
 * Characteristic UUIDs: Unique IDs for each characteristic within those services (e.g., Heart Rate Measurement, Battery Level).
 *  - To Do: Find the characteristics associated with reading and writing to the device
 *
 * Descriptor UUIDs: Such as the Client Characteristic Configuration Descriptor (CCCD) used to enable notifications, typically 00002902-0000-1000-8000-00805f9b34fb.
 */

/**  Pre-requisite domain considerations
 *  The serialized data has to come over the wire, and the code below examples how the react-native-ble-plx library API can
 *  be used to access the data. This is a concern that should be separated in its own module but being aware of the high
 *  -level objects and the API they provide is necessary for implementing DataSerialization.ts.
 *  More examples and information can be found here -> https://dotintent.github.io/react-native-ble-plx/#characteristic
 */

// This would be the technical entry point for the data serialization user story. There is required set up code to deal with handling the active
// bluetooth connection and discovering available services, but I am  separating those concerns with a higher level BLE connection
// manager. This class will only be responsible for querying the connection status and behaving accordingly.

/**
 * This device should be exported by a module that handles the BLE connection components. The DataSerialization.ts class
 * can use the reference to this object to interact with the required characteristics for reading/writing data.
 * device
 *   .connect()
 *   .then(device => {
 *     return device.discoverAllServicesAndCharacteristics()
 *   })
 *   .then(device => {
 *     // A fully functional connection you can use, now you can read, write and monitor values
 *     // This is where messages can be read. The characteristic associated with the serial communication can be accessed
 *     // starting here ->
 *   .readCharacteristicForService(serviceUUID(bluetooth module unique ID), characteristicUUID(reading/writing component associated
 *   with the bluetooth module)
 *   .then(characteristic => {
 *     console.log('Read characteristic value:', characteristic.value)
 *   })
 *   .catch(error => {
 *     console.error('Read characteristic error:', error)
 *   })
 *   })
 *   .catch(error => {
 *     // Handle errors
 *   })
 */

// The characteristic associated with reading/writing can be used here

// Load the file containing all the protobuf functions generated by the protoc compiler
var messages = require('../Resources/IBDC_pb');



/*Task#103 Serialize responses and de-serialize requests (DONE)
    Serialization To Dos:
        1. Create a valid message type
        2. Encode message type as a proto message

    De-serialization To Dos:
        1. Create object from over the wire
*/
// Create a new message of a type defined in IBDC.proto
var deviceStatus = new messages.DeviceStatus();

// Set message fields
deviceStatus.setBatteryPercent(50);
deviceStatus.setProtocolVersion(2);
deviceStatus.setPendingEvents(10);
deviceStatus.setStorageAvailablePercent(35);

// Serialize the message into binary data (in protobuf wire format).
console.log('payload as a json object', deviceStatus.toObject());
console.log('payload as proto encoded bytes', deviceStatus.serializeBinary());



// Equivalent of a byte array in Java. This is how protobuf represents data once serialized
let bytes: Uint8Array = [0, 3, 7, 12, 4];

// De-serialize the message
let message = messages.DeviceStatus.deserializeBinary(deviceStatus.serializeBinary());
console.log('message decoding as a json object', message.toObject());
log_communication("sending", message, message.toString(), "database");

/** Serializing and de-serializing data is not a problem when the type information is known before runtime.
*   Issues arise when the data type being received over the connection is dynamic. Two issues are:
*       1. How will each message be de-limited from the all the other messages in the received buffer?
*       2. How will we know which de-serializing function to use if the type of message is not known?
*/


// Task#102 Create communication log

// Detailed receipts upon send and delivery of serialized data can help developers determine if there are any data
// transmission errors. Certain messages are time-sensitive. It is important that the phone receives certain messages in its
// entirety or record the necessary information to retrieve the data at a later time.
// Messages will be logged in three places:
    // 1. When bytes are detected at the GATT Characteristic level (receiving)
    // 2. After data de-serialization/serialization attempt (receiving and sending)
    // 3. When a message is sent over the wire or to the database (sending)
// These are all either data transformation points or points where the data is being sent over an API. These are places
// where data integrity and or transmission cannot be guaranteed. Logging at these points ensures the correct component
// can be investigated when searching for errors.

// All communication logs should have the following: Date and Time, Connection Status[isConnectedToDevice](extensible array),
// Send or Receive, raw bytes or text attempted to be sent/stored.

/**
 *
 * @param message_direction 0 for received, 1 for sending
 * @param bytes the raw bytes received over the wire
 * @param text the data that has been deserialized on the client side
 * @param dest either the database or the IBDC device
 * @param file the file to write to
 */
function log_communication(message_direction: string, bytes: uint8[], text: string, dest: string, file: string =  "./communicationLog"): void {
    // Get date and time
    // Get device connection status
    const now: Date = new Date();
    const timestamp: string = (now.toLocaleString() + " Ms Elapsed:" + now.getMilliseconds());
    console.log(message_direction);
    console.log(getDeviceStatus());
    console.log(bytes);
    console.log(text);
    console.log(dest);
    const log: string = timestamp + "|" + message_direction + "|" + bytes.toString() + "|" + dest + "\n";
    if (file == undefined) {
        fs.writeFile(file, log, (err) => {
            if (err) {
                console.log(err);
            }
        } )
    }
    else {
        fs.appendFile(file, log, (err) => {
            if (err) {
                console.log("This is it?");
                console.log(err);
            }
        })
    }

}




// Task#88 Encapsulate data serialization logic

// What states would a DataSerializer need? What does a state diagram look like when considering asynchronicity?
// STATES: INITIALIZING, READY, SHUT_DOWN, ERROR
    // INITIALIZING: Determine connection status to database, log file, and the BLE connection.
        // Trigger -> Phone app powered on
        // Guards: []
    // READY: Ready to receive and send messages asynchronously.
        // Trigger -> all initialization flags are green
        // Guards: []
    // SHUTTING_DOWN: Save all data in receive and send buffers to be re-instated later. Write special log.
        // Trigger -> User exits the application or device connection is lost
        // Guards: []







// !UPDATE! This is not a valid strategy as it is not guaranteed that a message will fit in a single packet.
/** Potential solution to problem 1.
 *  As messages are received, each Uint8Array(byte array) is added to the buffer. This creates the
 *  concept of a defined start-end to each message. Each message is an element in the buffer.
 */

let buffer: Uint8Array[]; // Not feasible unless the packets are arranged into a single message before being placed
// into the array











